# -*- coding: utf-8 -*-
"""Camia_Namuhmuh

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwVE-x5tRxBao_7SPC0MKU2tyvr3c8FE
"""

print("Russell Jake A. Namuhmuh")